version: "3.7"

# Configuration to work with a local non-dockerized Gossip node
# For local testing and quick debugging
#
# HOW TO USE: Start a Gossip node, then run
#
# docker-compose -f docker/docker-compose.local.yml up -d

services:
  prometheus:
    build:
      context: prometheus
      args:
        # Linux:  localhost:8088
        # MacOSX: host.docker.internal:8088
        GOSSIP_URL: host.docker.internal:8088
    restart: always
    volumes:
      - "prometheus:/prometheus"
    ports:
      - 9090:9090

  grafana:
    build: grafana
    restart: always
    volumes:
      - "grafana:/var/lib/grafana"
      - "../dashboards:/dashboards"
    environment:
      # Linux:  http://localhost:9090
      # MacOSX: http://host.docker.internal:9090
      PROMETHEUS_URL: http://host.docker.internal:9090
    ports:
      - 3000:3000

volumes:
  prometheus:
  grafana:
