{
 "title": "Seaport Gossip",
 "tags": [ "seaport_gossip" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Provider", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Provider Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(eth_provider_requests)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chain Height",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chain_height", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Provider Requests By Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(method) (rate(eth_provider_responses[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Provider Avg Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "rate(eth_provider_response_time_milliseconds_sum[5m]) / rate(eth_provider_response_time_milliseconds_count[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Provider Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(error) (eth_provider_responses{error!=\"undefined\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Orders Added/Removed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "orders_added", "legendFormat": "added ({{instance}})" },
    { "expr": "orders_deleted", "legendFormat": "removed ({{instance}})" }
   ]
  },
  {
   "title": "Total Orders In Database",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "orders_total_count_valid", "legendFormat": "valid ({{instance}})" },
    { "expr": "orders_total_count_invalid", "legendFormat": "invalid ({{instance}})" }
   ]
  },
  {
   "title": "Orders Validated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "rate(orders_validated[$__rate_interval])",
     "legendFormat": "valid ({{instance}})"
    },
    {
     "expr": "rate(orders_invalidated[$__rate_interval])",
     "legendFormat": "invalid ({{instance}})"
    }
   ]
  },
  {
   "title": "Order Errors and Warnings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "order_errors_and_warnings", "legendFormat": "{{issue}} ({{instance}})" }
   ]
  },
  {
   "title": "Orders Ingested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "rate(orders_ingested_opensea[$__rate_interval])",
     "legendFormat": "OpenSea, addedToDB={{addedToDB}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data sent/received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 51 },
   "targets": [
    {
     "expr": "rate(libp2p_data_transfer_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_global_stats[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Gossip Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_protocol__meshsub_1_1_0_bytes[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Identify-Push Protocol Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_protocol__ipfs_id_push_1_0_0_bytes[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Identify Protocol Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_protocol__ipfs_id_1_0_0_bytes[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Connection Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_connections",
     "legendFormat": "{{libp2p_connection_manager_connections}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Total Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_protocol_streams_total",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Streams Per Connection (90th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
   "targets": [
    {
     "expr": "libp2p_connection_manager_protocol_streams_per_connection_90th_percentile",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Pending dials",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
   "targets": [
    { "expr": "libp2p_dialler_pending_dials", "legendFormat": "pending dials ({{instance}})" },
    {
     "expr": "libp2p_dialler_pending_dial_targets",
     "legendFormat": "pending dial targets ({{instance}})"
    }
   ]
  },
  {
   "title": "Transport manager listeners",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
   "targets": [
    {
     "expr": "libp2p_transport_manager_listeners",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TCP transport dialer errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
   "targets": [
    {
     "expr": "rate(libp2p_tcp_dialer_errors_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "DHT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 101 } },
  {
   "title": "DHT query time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "libp2p_kad_dht_wan_query_time_seconds",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DHT ping queue size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "targets": [
    {
     "expr": "libp2p_kad_dht_wan_ping_queue_size",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DHT ping running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "libp2p_kad_dht_wan_ping_running",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DHT routing table size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "libp2p_kad_dht_wan_routing_table_size",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Node.js", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 118 } },
  {
   "title": "% CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 119 },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total[$__rate_interval]) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage (mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "nodejs_memory_usage_bytes / 1000000",
     "legendFormat": "{{memory}} ({{instance}})"
    }
   ]
  },
  {
   "title": "External memory usage (mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "nodejs_external_memory_bytes / 1000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Node.js total active resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "targets": [
    { "expr": "nodejs_active_resources_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Node.js active resources",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    { "expr": "nodejs_active_resources", "legendFormat": "{{type}} ({{instance}})" }
   ]
  },
  {
   "title": "Node.js total active handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "targets": [
    { "expr": "nodejs_active_handles_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Node.js active handles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "targets": [
    { "expr": "nodejs_active_handles", "legendFormat": "{{type}} ({{instance}})" }
   ]
  },
  {
   "title": "Node.js total active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "targets": [
    { "expr": "nodejs_active_requests_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Node.js active requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "targets": [
    { "expr": "nodejs_active_requests", "legendFormat": "{{type}} ({{instance}})" }
   ]
  },
  {
   "title": "Node.js heap size (mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes / 1000000",
     "legendFormat": "used ({{instance}})"
    },
    {
     "expr": "nodejs_heap_size_total_bytes / 1000000",
     "legendFormat": "total ({{instance}})"
    }
   ]
  },
  {
   "title": "Node.js heap space size (mb)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "targets": [
    {
     "expr": "nodejs_heap_size_used_bytes / 1000000",
     "legendFormat": "used ({{instance}})"
    },
    {
     "expr": "nodejs_heap_space_size_total_bytes / 1000000",
     "legendFormat": "total: {{space}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Node.js heap space size available mb",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes / 1000000",
     "legendFormat": "{{space}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Node.js garbage collection seconds count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count",
     "legendFormat": "{{kind}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Node.js EventLoop lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_p50_seconds",
     "legendFormat": "P50 ({{instance}})"
    },
    {
     "expr": "nodejs_eventloop_lag_p90_seconds",
     "legendFormat": "P90 ({{instance}})"
    },
    {
     "expr": "nodejs_eventloop_lag_p99_seconds",
     "legendFormat": "P99 ({{instance}})"
    }
   ]
  }
 ]
}