{
 "title": "Libp2p",
 "tags": [ "seaport_gossip" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "rate_interval",
    "label": "rate() interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Data sent/received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 2 },
   "targets": [
    {
     "expr": "rate(libp2p_data_transfer_bytes_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_global_stats[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Gossip Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_protocol__meshsub_1_1_0_bytes[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Identify-Push Protocol Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_protocol__ipfs_id_push_1_0_0_bytes[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Identify Protocol Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(libp2p_protocol__ipfs_id_1_0_0_bytes[$rate_interval])",
     "legendFormat": "{{direction}}"
    }
   ]
  },
  {
   "title": "Connection Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "libp2p_connection_manager_connections",
       "legendFormat": "{{libp2p_connection_manager_connections}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Total Streams",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "libp2p_connection_manager_protocol_streams_total",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Streams Per Connection (90th percentile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "libp2p_connection_manager_protocol_streams_per_connection_90th_percentile",
       "legendFormat": "{{protocol}}"
      }
     ]
    },
    {
     "title": "Pending dials",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      { "expr": "libp2p_dialler_pending_dials", "legendFormat": "pending dials ({{instance}})" },
      {
       "expr": "libp2p_dialler_pending_dial_targets",
       "legendFormat": "pending dial targets ({{instance}})"
      }
     ]
    },
    {
     "title": "Transport manager listeners",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "libp2p_transport_manager_listeners",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "TCP transport dialer errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "rate(libp2p_tcp_dialer_errors_total[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "DHT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "DHT query time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "libp2p_kad_dht_wan_query_time_seconds",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DHT ping queue size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "libp2p_kad_dht_wan_ping_queue_size",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DHT ping running",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "libp2p_kad_dht_wan_ping_running",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "DHT routing table size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "libp2p_kad_dht_wan_routing_table_size",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Node.js",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "% CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 6, "y": 5 },
     "targets": [
      {
       "expr": "rate(process_cpu_user_seconds_total[$__rate_interval]) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory usage (mb)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "nodejs_memory_usage_bytes / 1000000",
       "legendFormat": "{{memory}} ({{instance}})"
      }
     ]
    },
    {
     "title": "External memory usage (mb)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "nodejs_external_memory_bytes / 1000000",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node.js total active resources",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "targets": [
      { "expr": "nodejs_active_resources_total", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node.js active resources",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      { "expr": "nodejs_active_resources", "legendFormat": "{{type}} ({{instance}})" }
     ]
    },
    {
     "title": "Node.js total active handles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "targets": [
      { "expr": "nodejs_active_handles_total", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node.js active handles",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      { "expr": "nodejs_active_handles", "legendFormat": "{{type}} ({{instance}})" }
     ]
    },
    {
     "title": "Node.js total active requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "targets": [
      { "expr": "nodejs_active_requests_total", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Node.js active requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "targets": [
      { "expr": "nodejs_active_requests", "legendFormat": "{{type}} ({{instance}})" }
     ]
    },
    {
     "title": "Node.js heap size (mb)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes / 1000000",
       "legendFormat": "used ({{instance}})"
      },
      {
       "expr": "nodejs_heap_size_total_bytes / 1000000",
       "legendFormat": "total ({{instance}})"
      }
     ]
    },
    {
     "title": "Node.js heap space size (mb)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "nodejs_heap_size_used_bytes / 1000000",
       "legendFormat": "used ({{instance}})"
      },
      {
       "expr": "nodejs_heap_space_size_total_bytes / 1000000",
       "legendFormat": "total: {{space}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Node.js heap space size available mb",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "targets": [
      {
       "expr": "nodejs_heap_space_size_available_bytes / 1000000",
       "legendFormat": "{{space}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Node.js garbage collection seconds count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "targets": [
      {
       "expr": "nodejs_gc_duration_seconds_count",
       "legendFormat": "{{kind}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Node.js EventLoop lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "nodejs_eventloop_lag_p50_seconds",
       "legendFormat": "P50 ({{instance}})"
      },
      {
       "expr": "nodejs_eventloop_lag_p90_seconds",
       "legendFormat": "P90 ({{instance}})"
      },
      {
       "expr": "nodejs_eventloop_lag_p99_seconds",
       "legendFormat": "P99 ({{instance}})"
      }
     ]
    }
   ]
  }
 ]
}